"""Theme lexicons for subject-area assessment."""

from __future__ import annotations

from school_capture.models import SubjectArea

AREA_LEXICONS: dict[SubjectArea, dict[str, tuple[str, ...]]] = {
    SubjectArea.CURRICULUM: {
        "breadth": (
            "broad",
            "balanced",
            "ambitious",
            "knowledge-rich",
            "curriculum",
            "subjects",
            "gcse",
            "a level",
            "a-level",
            "options",
            "humanities",
            "languages",
            "stem",
            "reading",
            "writing",
            "mathematics",
            "science",
            "phonics",
            "key stage",
        ),
        "quality": (
            "high expectations",
            "achieve well",
            "progress",
            "sequenced",
            "coherent",
            "depth",
            "mastery",
            "stretch",
            "challenge",
        ),
    },
    SubjectArea.ENRICHMENT: {
        "breadth": (
            "club",
            "clubs",
            "sport",
            "music",
            "drama",
            "art",
            "orchestra",
            "choir",
            "trip",
            "visit",
            "residential",
            "enrichment",
            "extra-curricular",
            "after school",
            "competition",
            "festival",
        ),
        "quality": (
            "wide range",
            "opportunities",
            "develop talents",
            "interests",
            "participate",
            "represent",
            "award",
        ),
    },
    SubjectArea.ETHOS: {
        "breadth": (
            "values",
            "ethos",
            "vision",
            "mission",
            "respect",
            "kindness",
            "inclusive",
            "caring",
            "community",
            "character",
            "spiritual",
            "moral",
            "british values",
            "faith",
        ),
        "quality": (
            "proud",
            "happy",
            "safe",
            "nurturing",
            "supportive",
            "welcoming",
            "belong",
        ),
    },
    SubjectArea.BEHAVIOUR: {
        "breadth": (
            "behaviour",
            "behavior",
            "pastoral",
            "wellbeing",
            "well-being",
            "safeguarding",
            "anti-bullying",
            "discipline",
            "attendance",
        ),
        "quality": (
            "calm",
            "positive",
            "respectful",
            "high standards",
            "safe environment",
        ),
    },
    SubjectArea.SEND: {
        "breadth": (
            "send",
            "sen",
            "special educational",
            "inclusion",
            "ehcp",
            "accessibility",
            "differentiat",
            "support needs",
        ),
        "quality": (
            "inclusive",
            "individual",
            "tailored",
            "access",
            "reasonable adjustment",
        ),
    },
    SubjectArea.COMMUNITY: {
        "breadth": (
            "community",
            "parents",
            "families",
            "governors",
            "pta",
            "partnership",
            "local",
            "charity",
            "fundraise",
            "volunteer",
        ),
        "quality": (
            "together",
            "engage",
            "support families",
            "wider community",
        ),
    },
}

SECTION_TO_AREA: dict[str, SubjectArea] = {
    "curriculum": SubjectArea.CURRICULUM,
    "enrichment": SubjectArea.ENRICHMENT,
    "ethos": SubjectArea.ETHOS,
    "behaviour": SubjectArea.BEHAVIOUR,
    "send": SubjectArea.SEND,
    "community": SubjectArea.COMMUNITY,
    "homepage": SubjectArea.ETHOS,
    "general": SubjectArea.ETHOS,
    "local-news": SubjectArea.COMMUNITY,
    "social": SubjectArea.ENRICHMENT,
}
