"""Known concrete provision / activity / subject labels."""

from __future__ import annotations

PROVISION_TERMS: tuple[str, ...] = (
    "breakfast club",
    "after-school club",
    "after school club",
    "wraparound care",
    "wrap-around care",
    "wrap around care",
    "after-school care",
    "after school care",
    "holiday club",
    "holiday provision",
    "extended day",
    "early birds",
    "late stay",
    "childcare",
    "homework club",
    "study support",
)

ACTIVITY_TERMS: tuple[str, ...] = (
    "football",
    "rugby",
    "netball",
    "hockey",
    "cricket",
    "athletics",
    "swimming",
    "gymnastics",
    "dance",
    "ballet",
    "choir",
    "orchestra",
    "band",
    "music",
    "drama",
    "theatre",
    "art club",
    "chess",
    "coding",
    "robotics",
    "debate",
    "gardening",
    "cooking",
    "science club",
    "tennis",
    "badminton",
    "basketball",
    "volleyball",
    "table tennis",
    "karate",
    "judo",
    "fencing",
    "archery",
    "sailing",
    "rowing",
    "cadets",
    "duke of edinburgh",
    "young leaders",
    "school council",
    "eco club",
    "photography",
)

CURRICULUM_SUBJECT_TERMS: tuple[str, ...] = (
    "english",
    "mathematics",
    "maths",
    "science",
    "biology",
    "chemistry",
    "physics",
    "history",
    "geography",
    "french",
    "spanish",
    "german",
    "latin",
    "computer science",
    "computing",
    "design technology",
    "food technology",
    "religious education",
    "pshe",
    "citizenship",
    "art",
    "music",
    "drama",
    "pe",
    "physical education",
)
