"""URL and heading patterns for thematic school website sections."""

from __future__ import annotations

SECTION_PATTERNS: dict[str, tuple[str, ...]] = {
    "curriculum": (
        "curriculum",
        "subjects",
        "subject-curriculum",
        "curriculum-overview",
        "learning",
        "academic",
        "key-stage",
        "keystage",
        "gcse",
        "a-level",
        "alevel",
        "options",
        "timetable",
        "reading",
        "maths",
        "science",
        "ks1",
        "ks2",
        "ks3",
        "ks4",
    ),
    "enrichment": (
        "enrichment",
        "extra-curricular",
        "extracurricular",
        "clubs",
        "activities",
        "sport",
        "music",
        "drama",
        "trips",
        "visits",
        "after-school",
        "afterschool",
        "wraparound",
        "wrap-around",
        "breakfast club",
        "childcare",
        "extended day",
        "holiday club",
    ),
    "ethos": (
        "ethos",
        "values",
        "vision",
        "mission",
        "aims",
        "about",
        "welcome",
        "character",
        "spiritual",
        "moral",
        "british-values",
    ),
    "behaviour": (
        "behaviour",
        "behavior",
        "pastoral",
        "wellbeing",
        "well-being",
        "safeguarding",
        "anti-bullying",
        "discipline",
    ),
    "send": (
        "send",
        "sen",
        "special-needs",
        "special educational",
        "send-provision",
        "send-information",
        "local-offer",
        "senco",
        "ehcp",
    ),
    "community": (
        "community",
        "parents",
        "governors",
        "pta",
        "friends-of",
        "partnership",
        "charity",
        "open day",
    ),
}

# High-value page targets (boost discovery score).
PRIORITY_URL_TERMS: dict[str, tuple[str, ...]] = {
    "enrichment": ("clubs", "extra-curricular", "wraparound", "breakfast"),
    "curriculum": ("curriculum", "subjects", "options"),
    "send": ("send", "sen", "local-offer", "senco"),
}
